"""add_reports_table

Revision ID: afc2f8425aa0
Revises: ee55974a0232
Create Date: 2026-06-15 22:45:17.192304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc2f8425aa0'
down_revision: Union[str, Sequence[str], None] = 'ee55974a0232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talent_id', 'month', name='uq_report_talent_month')
    )
    op.create_index(op.f('ix_reports_month'), 'reports', ['month'], unique=False)
    op.create_index(op.f('ix_reports_talent_id'), 'reports', ['talent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_talent_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_month'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
