"""add deals, deal_stage_events, sync_logs

Revision ID: c35f623eaa21
Revises: 324116cbf0dd
Create Date: 2026-06-13 13:50:54.460740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35f623eaa21'
down_revision: Union[str, Sequence[str], None] = '324116cbf0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipedrive_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('is_sin_cotizar', sa.Boolean(), nullable=False),
    sa.Column('loss_reason', sa.String(), nullable=True),
    sa.Column('brand_category', sa.String(), nullable=True),
    sa.Column('expected_collection_date', sa.String(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=False),
    sa.Column('add_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_pipedrive_id'), 'deals', ['pipedrive_id'], unique=True)
    op.create_index(op.f('ix_deals_talent_id'), 'deals', ['talent_id'], unique=False)
    op.create_table('deal_stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_pipedrive_id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_stage_events_deal_pipedrive_id'), 'deal_stage_events', ['deal_pipedrive_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_deal_stage_events_deal_pipedrive_id'), table_name='deal_stage_events')
    op.drop_table('deal_stage_events')
    op.drop_index(op.f('ix_deals_talent_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_pipedrive_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
