"""add leads table

Revision ID: d48d69b17ea6
Revises: c35f623eaa21
Create Date: 2026-06-14 17:24:28.081554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48d69b17ea6'
down_revision: Union[str, Sequence[str], None] = 'c35f623eaa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_row_id', sa.Integer(), nullable=False),
    sa.Column('remitente_email', sa.String(), nullable=False),
    sa.Column('remitente_nombre', sa.String(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('status_filtrado', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('score_calidad', sa.Integer(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('convertido_a_prospecto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_sheet_row_id'), 'leads', ['sheet_row_id'], unique=True)
    op.create_index(op.f('ix_leads_status_filtrado'), 'leads', ['status_filtrado'], unique=False)
    op.create_index(op.f('ix_leads_talent_id'), 'leads', ['talent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_talent_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status_filtrado'), table_name='leads')
    op.drop_index(op.f('ix_leads_sheet_row_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
