"""add-deal-status-stage-indices

Revision ID: d9955ae215ef
Revises: afc2f8425aa0
Create Date: 2026-06-16 22:06:12.446037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9955ae215ef'
down_revision: Union[str, Sequence[str], None] = 'afc2f8425aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deal_stage_events_talent_id'), 'deal_stage_events', ['talent_id'], unique=False)
    op.create_index(op.f('ix_deals_stage_name'), 'deals', ['stage_name'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_stage_name'), table_name='deals')
    op.drop_index(op.f('ix_deal_stage_events_talent_id'), table_name='deal_stage_events')
    # ### end Alembic commands ###
