"""add trello_cards table

Revision ID: ee55974a0232
Revises: d48d69b17ea6
Create Date: 2026-06-14 22:00:44.673532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee55974a0232'
down_revision: Union[str, Sequence[str], None] = 'd48d69b17ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trello_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trello_card_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('list_id', sa.String(), nullable=False),
    sa.Column('list_name', sa.String(), nullable=False),
    sa.Column('list_state', sa.String(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('pipedrive_deal_id_desc', sa.Integer(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trello_cards_deal_id'), 'trello_cards', ['deal_id'], unique=False)
    op.create_index(op.f('ix_trello_cards_trello_card_id'), 'trello_cards', ['trello_card_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trello_cards_trello_card_id'), table_name='trello_cards')
    op.drop_index(op.f('ix_trello_cards_deal_id'), table_name='trello_cards')
    op.drop_table('trello_cards')
    # ### end Alembic commands ###
